Homework 3
fintech-kotlin/strelchenko-cashback-service pull request #3
Opened 2020-03-09 23:14 UTC by damn1kk

# Выполнено задание №

## В процесс было сделано:
 - реализовал интеграционные сервисы для получения информации, сохранения в БД и отправки уведомления.

## PR чеклист:
 - [x] В Project выставлен `Tinkoff "Java to Kotlin"`
 - [x] Добавлен label с номером домашнего задания

2020-03-10 17:04 UTC, ArtyomIvanov commented on src/main/kotlin/ru/tinkoff/fintech/client/CardServiceClientImpl.kt
> +    @Value("\${services.url.card}")
Внедрять проперти через @Value лучше в конструкторе, это позволит сделать филд read-only, а также упасть при старте приложения есть вдруг значение проперти не установлено. При lateinit данное падение произойдет уже только в рантайме при первом обращении к филду.
```
@Service
class CardServiceClientImpl(
    @Value("\${services.url.card}")
    private val url: String
) : CardServiceClient 
```

2020-03-10 17:08 UTC, ArtyomIvanov commented on src/main/kotlin/ru/tinkoff/fintech/client/CardServiceClientImpl.kt
> +        val template = RestTemplate()
У тебя абсолютно во всех клиентах при каждом обращении происходит создание нового RestTemplate, что в итоге плодит мусор и дополнительные сборки мусора в твоем приложении. Если конфигурация RestTemplate везде одинаковая, то можно создать бин RestTemplate где-то на уровне конфигураций приложения (обычное корневой пакет проекта configuration) или сделать топ-лвл синглтон и использовать везде его.

```
object : RestTemplate
```

2020-03-10 17:23 UTC, ArtyomIvanov commented on src/main/kotlin/ru/tinkoff/fintech/client/CardServiceClientImpl.kt
> +        return template.getForObject("$url$cardNumber", Card::class.java)!!
Довольно опасный способ использовать RestTemplate, в продакшн бы такой код не прошел. Лучше использовать метод у RestTemplate который возвращает ResponseEntity и делать проверку на HttpStatus == 200 и body != null, в противном случае кидать какой-то осмысленный exception по стеку выше, а не дефолтный RestClientException. Так как клиентов много, то можно написать функцию расширения для RestTemplate, содержащую в себе и логику вызова и обработку кейсов  описанных выше, тогда в дальнейшем если понадобится поправить кейс или добавить новый, то это надо будет делать лишь в одном месте.

2020-03-10 17:32 UTC, ArtyomIvanov commented on src/main/kotlin/ru/tinkoff/fintech/listener/TransactionListener.kt
> +    val transactionService: TransactionService
Обычно по умолчанию мы не хотим чтобы зависимости которые мы инжектим были публичными, чтобы какой-то другой компонент, который заинжектит в себя TransactionListener автоматом получил доступ и к  TransactionService (одна из причин создания для всего интерфейсов и внедрения зависимостей именно через интерфейсы кстати такая же). Так что лучше все что инжектится делать private, а если вдруг почему-то надо сделать public, то еще раз просмотреть код на предмет того, а не делаем ли мы что-то не так.

2020-03-10 17:37 UTC, ArtyomIvanov commented on src/main/kotlin/ru/tinkoff/fintech/service/transaction/TransactionServiceImpl.kt
> +        val card = cardService.getCard(transaction.cardNumber)
Пока что логики по обработке исключений не закладывалось, но тем не менее падать до самого лисенера если вдруг где-то словили эксепшн без всякого логгирования - плохо. Оберни все в try/catch и добавь лог того что мы начали обрабатывать транзакцию и успешно обработали или упали.

2020-03-10 17:45 UTC, ArtyomIvanov requested changes
Если суммировать все по пул-реквесту:
1. Заведи отдельный бин или топ-лвл синглтон для RestTemplate
2. @Value лучше инжектить в конструкторе
3. Все внедряемые зависимости должны быть по умолчанию private 
4. Добавить обработку ответа RestTemplate по статус коду и наличию body.
5. Где-то на верхней точке входа (в нашем случае кафка лиснр или TransactionListener) добавить логирование обработки транзакции.

В целом очень достойная реализация, с доработкой сказанных выше пунктов станет идеальной))

2020-03-10 20:12 UTC, damn1kk commented on src/main/kotlin/ru/tinkoff/fintech/client/CardServiceClientImpl.kt
> +    @Value("\${services.url.card}")
Устранил.

2020-03-10 20:12 UTC, damn1kk commented on src/main/kotlin/ru/tinkoff/fintech/client/CardServiceClientImpl.kt
> +        val template = RestTemplate()
Исправил.

2020-03-10 20:15 UTC, damn1kk commented on src/main/kotlin/ru/tinkoff/fintech/client/CardServiceClientImpl.kt
> +        return template.getForObject("$url$cardNumber", Card::class.java)!!
Добавил обработчик ошибок DefaultResponseErrorHandler для проверок статусов.
По-хорошему и обработку пустого тела ответа нужно было бы через него сделать, но т.к. мы тут изучаем Котлин, сделал обработку пустого тела через extension функцию getForObjectWithEmptyBodyResponseCheck.

2020-03-10 20:15 UTC, damn1kk commented on src/main/kotlin/ru/tinkoff/fintech/listener/TransactionListener.kt
> +    val transactionService: TransactionService
Исправил.

2020-03-10 20:16 UTC, damn1kk commented on src/main/kotlin/ru/tinkoff/fintech/service/transaction/TransactionServiceImpl.kt
> +        val card = cardService.getCard(transaction.cardNumber)
Добавил логгирование, но на уровне лисенера, т.к. у меня метод handleTransaction имеет две точки выхода логгировать там мне показалось не очень красиво.

2020-03-11 09:14 UTC, ArtyomIvanov approved these changes
Можно мерджить

2020-03-11 09:18 UTC, merged